/**
 * Twilio Integration
 * 
 * This module centralizes Twilio configuration and exposes helper functions
 * for sending SMS (and, optionally, WhatsApp messages) from the RealLeads backend.
 * It reads credentials from environment variables and wraps the Twilio SDK in
 * a small, typed interface.
 * 
 * DEPENDENCIES:
 * - twilio: Twilio Node.js SDK
 * 
 * ENVIRONMENT VARIABLES:
 * - TWILIO_ACCOUNT_SID: Twilio account SID (required)
 * - TWILIO_AUTH_TOKEN: Twilio auth token (required)
 * - TWILIO_FROM_NUMBER: Twilio phone number for SMS (preferred)
 * - TWILIO_SMS_NUMBER: Fallback SMS number if TWILIO_FROM_NUMBER not set
 * - TWILIO_WHATSAPP_FROM: WhatsApp sender (e.g., "whatsapp:+1415...") (optional)
 * 
 * INTEGRATIONS:
 * - Used by: backend/src/executor/actions/send-sms.ts
 * - Used by: backend/src/executor/actions/send-whatsapp.ts
 * - Used by: backend/src/routes/pending-messages.ts (for approved messages)
 */

import type { Twilio } from "twilio";
import twilio from "twilio";

// ============================================================================
// Types
// ============================================================================

/**
 * Basic argument shape for sending a message
 */
export interface SendMessageParams {
  /** Recipient in E.164 format, e.g. +14155551234 or whatsapp:+14155551234 */
  to: string;
  
  /** Message body text (already generated by the orchestrator) */
  body: string;
}

/**
 * Result of sending a message via Twilio
 */
export interface SendMessageResult {
  /** Twilio message SID */
  sid: string;
  
  /** Message status */
  status: string;
  
  /** Recipient number */
  to: string;
  
  /** Sender number */
  from: string;
  
  /** Message body */
  body: string;
}

// ============================================================================
// Configuration
// ============================================================================

// Read shared Twilio credentials from environment variables
const accountSid = process.env.TWILIO_ACCOUNT_SID;
const authToken = process.env.TWILIO_AUTH_TOKEN;

// For SMS, prefer TWILIO_FROM_NUMBER, otherwise fall back to TWILIO_SMS_NUMBER
const smsFromNumber =
  process.env.TWILIO_FROM_NUMBER || process.env.TWILIO_SMS_NUMBER;

// For WhatsApp, we expect a "from" like: "whatsapp:+1415XXXXXXX"
const whatsappFrom = process.env.TWILIO_WHATSAPP_FROM;

// Fail fast if credentials are missing so we do not try to send with an unconfigured client
if (!accountSid || !authToken) {
  throw new Error(
    "Twilio configuration missing: TWILIO_ACCOUNT_SID or TWILIO_AUTH_TOKEN is not set."
  );
}

// Initialize a single Twilio client instance for reuse
const client: Twilio = twilio(accountSid, authToken);

// ============================================================================
// SMS Functions
// ============================================================================

/**
 * sendSms
 * 
 * Sends a standard SMS message using the configured Twilio phone number.
 * The message body text should already be in the desired tone (e.g. Mika).
 * 
 * @param params - Message parameters (to, body)
 * @returns Message result with SID, status, and details
 * @throws Error if SMS configuration is missing or send fails
 * 
 * @example
 * const result = await sendSms({
 *   to: '+14155551234',
 *   body: 'Hi Sarah! I found 3 properties that match your criteria...'
 * });
 */
export async function sendSms(
  params: SendMessageParams
): Promise<SendMessageResult> {
  const { to, body } = params;

  if (!smsFromNumber) {
    throw new Error(
      "Twilio SMS configuration error: TWILIO_FROM_NUMBER or TWILIO_SMS_NUMBER must be set."
    );
  }

  try {
    // Create and send SMS message via Twilio
    const message = await client.messages.create({
      from: smsFromNumber,
      to,
      body,
    });

    // Return standardized result
    return {
      sid: message.sid,
      status: message.status ?? "unknown",
      to: message.to ?? to,
      from: message.from ?? smsFromNumber,
      body,
    };
  } catch (error: any) {
    // Log error details for debugging
    console.error("Failed to send SMS via Twilio:", {
      message: error?.message,
      code: error?.code,
      moreInfo: error?.moreInfo,
    });

    throw new Error("Failed to send SMS via Twilio.");
  }
}

// ============================================================================
// WhatsApp Functions
// ============================================================================

/**
 * sendWhatsapp
 * 
 * Sends a WhatsApp message via Twilio. This requires that TWILIO_WHATSAPP_FROM
 * be configured with a sender like "whatsapp:+1415XXXXXXX". For now, this is
 * optional and can be wired up once WhatsApp is enabled on the Twilio account.
 * 
 * @param params - Message parameters (to, body)
 * @returns Message result with SID, status, and details
 * @throws Error if WhatsApp configuration is missing or send fails
 * 
 * @example
 * const result = await sendWhatsapp({
 *   to: '+14155551234',
 *   body: 'Hi Sarah! I found 3 properties that match your criteria...'
 * });
 */
export async function sendWhatsapp(
  params: SendMessageParams
): Promise<SendMessageResult> {
  const { to, body } = params;

  if (!whatsappFrom) {
    throw new Error(
      "Twilio WhatsApp configuration error: TWILIO_WHATSAPP_FROM is not set."
    );
  }

  // Ensure the recipient number is prefixed with "whatsapp:" as required by Twilio
  const toWithPrefix = to.startsWith("whatsapp:")
    ? to
    : `whatsapp:${to}`;

  try {
    // Create and send WhatsApp message via Twilio
    const message = await client.messages.create({
      from: whatsappFrom,
      to: toWithPrefix,
      body,
    });

    // Return standardized result
    return {
      sid: message.sid,
      status: message.status ?? "unknown",
      to: message.to ?? toWithPrefix,
      from: message.from ?? whatsappFrom,
      body,
    };
  } catch (error: any) {
    // Log error details for debugging
    console.error("Failed to send WhatsApp message via Twilio:", {
      message: error?.message,
      code: error?.code,
      moreInfo: error?.moreInfo,
    });

    throw new Error("Failed to send WhatsApp message via Twilio.");
  }
}

